font_family Liberation Mono
font_size 11

cursor_text_color #ffffff
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0
shell_integration no-cursor

enable_audio_bell no

window_padding_width 2

background #1a1a1a
foreground #c7c7c7

color0 #000000
color8 #686868

color1 #ff2600
color9 #ff6e67

color2 #00f909
color10 #5ffa68

color3 #fffb00
color11 #fffc67

color4 #3465a4
color12 #729fcf

color5 #ff40ff
color13 #ff77ff

color6 #50f9ff
color14 #60fdff

color7 #f0f0f0
color15 #ffffff

allow_hyperlinks yes
